---
- name: install nginx
  apt: name=nginx update_cache=yes
- name: copy nginx config file
  copy: src={{ config_src }} dest=/etc/nginx/sites-available/default
- name: enable configuration
  file: >
    dest=/etc/nginx/sites-enabled/default
    src=/etc/nginx/sites-available/default
    state=link
- name: copy index.html
  copy: src={{ index_file }} dest=/usr/share/nginx/html/index.html mode=0644
- name: restart nginx
  service: name=nginx state=restarted
