---
- name: add nginx siging key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
- name: add nginx repo
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/debian/ squeeze nginx"
- name: add nginx repo src
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/debian/ squeeze nginx"
- name: update apt
  apt: update_cache=yes cache_valid_time=1
- name: install nginx
  apt: name=nginx state=latest update_cache=yes
  notify:
    - restart nginx
