---
- name: install nginx
  apt: name=nginx update_cache=yes
- name: copy nginx config file
  copy: src={{ config_src }} dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: enable configuration
  file: >
    dest=/etc/nginx/sites-enabled/default
    src=/etc/nginx/sites-available/default
    state=link
  notify:
    - restart nginx
- name: ensure html directory exists
  file: path=/usr/share/nginx/html state=directory
  notify:
    - restart nginx
- name: copy index.html
  copy: src={{ index_file }} dest=/usr/share/nginx/html/index.html mode=0644
  notify:
    - restart nginx
