---
- name: Configure webserver with nginx
  hosts: webservers
  sudo: true
  roles:
    - joshualund.ruby-2_1
    - { role: nginx, config_src: 'files/nginx.conf', index_file: 'files/index.html' }
  
