---
- name: Configure webserver with nginx
  hosts: webservers
  sudo: true
  roles:
    - joshualund.ruby-2_1
    - nginx
    - memcached
    - mysql
  tasks:
    - name: install git
      apt: name=git update_cache=yes
