---
galaxy_info:
  author: Hector Castro
  description: An Ansible role to install Nginx.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - web
dependencies: []
