---
galaxy_info:
  author: Hector Castro
  description: An Ansible role for installing the Ruby programming language.
  company: Azavea Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - development
dependencies: []
