- name: Update and then safe upgrade installed packages
  apt:
    update_cache=yes
    upgrade=yes
  sudo: yes

- name: Apply sysctl settings
  sysctl:
    name={{ item.key }}
    value={{ item.value }}
  sudo: yes
  with_dict: preconf.sysctl
