---
- name: update apt
  command: apt-get update

- name: Install mysql
  apt: name={{ item }}
  with_items:
    - mysql-common
    - mysql-server
    - mysql-client

- name: Configure mysql
  copy: src=my.cnf dest=/etc/my.cnf
  notify: restart mysql
