---
- name: Add mysql repository
  command: apt-add-repository ppa:ondrej/mysql-5.6
  command: apt-get update

- name: Install mysql 5.6
  apt: name={{item}}
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6

- name: Enable and start mysql service
  service: name=mysql enabled=yes state=started