---
- name: Ensure redis dependencies are installd
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - "libjemalloc1"
  tags:
  - packages

- name: Ensure redis group is present
  group:
    gid: "{{contrail_redis_gid}}"
    name: "{{contrail_redis_group}}"
    state: present
  tags:
  - user

- name: Ensure redis user is present
  user:
    name: "{{contrail_redis_user}}"
    uid: "{{contrail_redis_uid}}"
    group: "{{contrail_redis_group}}"
    comment: "contrail redis user"
    home: "{{contrail_redis_user_dir}}"
    shell: "/bin/false"
    state: present
  tags:
  - user

- name: Ensure redis user directory
  file:
    path: "{{contrail_redis_user_dir}}"
    owner: "{{contrail_redis_user}}"
    group: "{{contrail_redis_group}}"
    mode: 0700
    state: directory
  tags:
  - user

- name: Ensure /var/run directory
  file:
    path: "{{contrail_redis_run_dir}}"
    owner: "{{contrail_redis_user}}"
    group: "{{contrail_redis_group}}"
    mode: 0755
    state: directory
  tags:
  - user

- name: Install redis-server package 1/2
  get_url:
    url: "http://us.archive.ubuntu.com/ubuntu/pool/universe/r/redis/redis-server_{{contrail_redis_version}}_amd64.deb"
    dest: "{{contrail_redis_user_dir}}/{{contrail_redis_version}}_amd64.deb"
  tags:
  - packages

- name: Install redis-server package 2/2
  shell: dpkg -i {{contrail_redis_user_dir}}/{{contrail_redis_version}}_amd64.deb
         creates=/usr/bin/redis-server
  tags:
  - packages

- name: Update the redis-server init script
  template:
    src: "redis-server"
    dest: "/etc/init.d/redis-{{contrail_redis_name}}"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
  - configuration

- name: Update the redis-uve configuration
  template:
    src: "redis-server.conf"
    dest: "/etc/redis/redis-{{contrail_redis_name}}.conf"
    owner: "{{contrail_redis_user}}"
    group: "{{contrail_redis_group}}"
    mode: 0644
  notify:
  - "restart redis-{{contrail_redis_name}}"
  tags:
  - configuration

- name: Ensure redis-server service is enabled
  service:
    name: "redis-{{contrail_redis_name}}"
    enabled: yes
    state: started
  tags:
  - serivce
