---
- name: Configure apt repository for nginx
  command: echo -e "deb http://nginx.org/packages/debian/ trusty nginx \n deb-src http://nginx.org/packages/debian/ trusty nginx" >> /etc/apt/sources.list

- name: Install nginx
  apt: name=nginx state=latest

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
