---
- name: update yum repo
  sudo: True
  yum: name=* state=latest

- name: update libselinux-python
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat"

- name: setup deploy
  sudo: True
  file:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    path: /var/www
    state: directory
  ignore_errors: True

- name: setup unicorn log directory
  sudo: True
  file:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744
    path: /var/log/unicorn
    state: directory
  ignore_errors: True

- name: setup var run directory
  sudo: True
  file:
    mode: 0777
    path: /var/run
    state: directory
  ignore_errors: True  

- name: setup unicorn pid file
  sudo: True
  file:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744
    path: /var/run/unicorn.pid
    state: touch
  ignore_errors: True