mysql_root_password: P@ssw0rd
mysql_databases:
  - name: example_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: example_user
    host: "%"
    password: password
    priv: "example_db.*:ALL"