---
- name: Install Memcached
  apt: pkg=memcached={{ memcached_version }} state=present

- name: Configure Memcached
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify:
    - Restart Memcached
